修正：Serviceの開始タイミング
MediaProjection開始前にForegroundServiceを開始済みの必要がある
java.lang.SecurityException: Media projections require a foreground service of type ServiceInfo.FOREGROUND_SERVICE_TYPE_MEDIA_PROJECTION